kind: pipeline
name: test 3.10

platform:
  os: linux
  arch: arm64

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/remotes/origin/main
    - refs/pull/**
    - refs/tags/v**

steps:
  - name: check style
    image: igur007/py3106allure:latest
    pull: if-not-exists
    commands:
    - pip3 install invoke
    - pip3 install uv
    - inv install-dev
    - . .venv/bin/activate

  - name: run unit tests
    depends_on:
      - check style
    image: igur007/py3106allure:latest
    pull: if-not-exists
    commands:
    - pip3 install invoke
    - . .venv/bin/activate
    - inv tests-coverage


  - name: allure report
    depends_on:
      - run unit tests
    image: igur007/drone-allure-server-plugin:latest
    pull: if-not-exists
    when:
      status:
        - failure
        - success
    environment:
      ALLURE_SERVER_URL: http://10.110.213.220:8080
    secrets: [DRONE_BUILD_NUMBER, DRONE_BUILD_LINK]